title: Dragon Well 龙井阁
email: 3189490169@qq.com
description: >-
  Welcome.
baseurl: ""
url: "https://frycan.github.io"

theme: minima
minima:
  show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 6
paginate_path: "/page:num/"
permalink: /:year/:month/:day/:title/

